Correção no repasse do nome de arquivos para verificação

diff --git a/.github/workflows/check_snake_case.yml b/.github/workflows/check_snake_case.yml
--- a/.github/workflows/check_snake_case.yml
+++ b/.github/workflows/check_snake_case.yml
@@ -13,8 +13,9 @@ jobs:
       - name: Analisa os arquivos 
         run: |
           find . -type f -name "*.py" | while read -r files; do 
-              if ! [[ $files =~  ^[a-z]+(_[a-z0-9]+)*\.py$ ]]; then
-                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $files esta fora do padrao"
+              file_name=$(basename "$files" .py)
+              if ! [[ $file_name =~  ^[a-z]+(_[a-z0-9]+)*$ ]]; then
+                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $file_name esta fora do padrao"
                   exit 1
               fi
           done
